// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujuaufitrfpawszjotwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqdWF1Zml0cmZwYXdzempvdHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDMwOTYsImV4cCI6MjA3MTgxOTA5Nn0.aK8rUXs7ooWUJYPBEsjtwAZFiN3Gef6zR1owSuayLE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});